"""
Django settings for ICAYS_SGC project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q*ryf%qrfk#%$*rvq=&ki(0@r2fj-kgiub*xud-0&dyj1-bncn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['34.207.123.61']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'ICAYS_BIT',
    'calidad',
    'jdirecto',
    'channels',
]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'ICAYS_SGC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ICAYS_SGC/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Configuración de Channels
ASGI_APPLICATION = 'ICAYS_SGC.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
VAPID_PRIVATE_KEY = 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1E3eHZySkhJL0wrWEMxNWEKRVArNmZtckJscldiTjNPczZyY25Gd3hOa3YyaFJBTkNBQVFCL213VjVmN09xTHNhUFN5YmZsTXR2Q1pieGFicgpQME5pVTJHWVlCWnBhTExwMlhDZlZ1d29lQUNINyt1TmI5NzBEU0dFYStUZmVXMGQ1bis5S3VmRwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=='  # Se generará automáticamente
VAPID_PUBLIC_KEY = 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFQWY1c0ZlWCt6cWk3R2owc20zNVRMYndtVzhXbQo2ejlEWWxOaG1HQVdhV2l5NmRsd24xYnNLSGdBaCsvcmpXL2U5QTBoaEd2azMzbHRIZVovdlNybnhnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=='   # Se generará automáticamente
VAPID_CLAIMS = {
    "sub": "mailto:webmaster@icays.com"  # Cambia esto por tu correo electrónico
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'ICAYS_BIT.CustomUser'
AUTH_BITA_MODEL = 'ICAYS_BIT.bita_cbap'

# URLs de autenticación
LOGIN_URL = 'login'  # Nombre de la URL de la vista de login
LOGIN_REDIRECT_URL = 'micriobiologyll'  # URL a la que redirigir después del login
LOGOUT_REDIRECT_URL = 'login'
CSRF_TRUSTED_ORIGINS = [
    'http://34.207.123.61',  # Agrega la URL de tu entorno de desarrollo
]
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Backends de autenticación
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_bits',  # Nombre de la base de datos que creaste en phpMyAdmin
        'USER': 'icays',             # Usuario de MySQL (por defecto es 'root' en XAMPP)
        'PASSWORD': 'admin144@',             # Contraseña de MySQL (por defecto está vacía en XAMPP)
        'HOST': 'localhost',       # Host de la base de datos
        'PORT': '3306',            # Puerto de MySQL (por defecto es 3306)
        'OPTIONS': {
            'sql_mode': 'STRICT_ALL_TABLES',  # Activa el modo estricto
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# settings.py
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = BASE_DIR / 'productionfiles'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
