# Generated by Django 5.1.6 on 2025-02-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(db_column='id_area', primary_key=True, serialize=False)),
                ('name_area', models.CharField(db_column='name_area', max_length=250)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('name_rol', models.CharField(db_column='name_rol', max_length=250)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='name_user', max_length=150)),
                ('last_name', models.CharField(db_column='last_name_user', max_length=150)),
                ('signature_user', models.CharField(db_column='signature_user', max_length=250)),
                ('email', models.EmailField(db_column='gmail_user', max_length=254, unique=True)),
                ('username', models.CharField(db_column='nameUs_user', max_length=150, unique=True)),
                ('password', models.CharField(db_column='pass_user', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('area_user', models.ForeignKey(db_column='area_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ICAYS_BIT.area')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('rol_user', models.ForeignKey(db_column='rol_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ICAYS_BIT.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
