# Generated by Django 5.1.6 on 2025-03-25 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCampoCbap',
            fields=[
                ('id_dc', models.AutoField(db_column='id_dc', primary_key=True, serialize=False)),
                ('fecha_siembra_dc', models.DateField(blank=True, db_column='fecha_siembra_dc', null=True)),
                ('hora_siembra_dc', models.TimeField(blank=True, db_column='hora_siembra_dc', null=True)),
                ('hora_incubacion_dc', models.TimeField(blank=True, db_column='hora_incubacion_dc', null=True)),
                ('procedimiento_dc', models.CharField(blank=True, db_column='procedimiento_dc', default='-', max_length=50, null=True)),
                ('equipo_incubacion_dc', models.CharField(blank=True, db_column='equipo_incubacion_dc', default='-', max_length=50, null=True)),
            ],
            options={
                'db_table': 'datos_campo',
            },
        ),
        migrations.CreateModel(
            name='bita_cbap',
            fields=[
                ('id_cbap', models.AutoField(db_column='id_cbap', primary_key=True, serialize=False)),
                ('nombre_cbap', models.CharField(blank=True, db_column='nombre_cbap', default='-', max_length=250, null=True)),
                ('pagina_cbap', models.IntegerField(db_column='pagina_cbap', default=0, null=True)),
                ('fecha_register_cbap', models.DateField(auto_now_add=True)),
                ('hora_register_cbap', models.TimeField(auto_now_add=True)),
                ('letra_analista_cbap', models.CharField(blank=True, db_column='numero_analista_cbap', default='---', max_length=250, null=True)),
                ('mes_muestra_cbap', models.CharField(blank=True, db_column='mes_muestra_cbap', default='-', max_length=250, null=True)),
                ('pagina_muestra_cbap', models.CharField(blank=True, db_column='pagina_muestra_cbap', default='---', max_length=250, null=True)),
                ('pagina_fosfato_cbap', models.CharField(blank=True, db_column='pagina_fosfato_cbap', default='---', max_length=250, null=True)),
                ('numero_fosfato_cbap', models.CharField(blank=True, db_column='numero_fosfato_cbap', default='---', max_length=250, null=True)),
                ('pagina_agar_cbap', models.CharField(blank=True, db_column='pagina_agar_cbap', default='---', max_length=250, null=True)),
                ('numero_agar_cbap', models.CharField(blank=True, db_column='numero_agar_cbap', default='---', max_length=250, null=True)),
                ('fecha_lectura_cbap', models.DateField(blank=True, db_column='fecha_lectura_cbap', null=True)),
                ('hora_lectura_cbap', models.TimeField(blank=True, db_column='hora_lectura_cbap', null=True)),
                ('observaciones_cbap', models.TextField(blank=True, db_column='observaciones_cbap', default='-', null=True)),
                ('firma_user', models.ForeignKey(db_column='signature_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bita_cbap', to=settings.AUTH_USER_MODEL)),
                ('id_dc_cbap', models.ForeignKey(db_column='id_dc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bita_cbap', to='ICAYS_BIT.datoscampocbap')),
            ],
            options={
                'db_table': 'bita_cbap',
                'ordering': ['-fecha_register_cbap', '-hora_register_cbap'],
            },
        ),
        migrations.CreateModel(
            name='Bitcoras_Cbap',
            fields=[
                ('id_bita_cbap', models.AutoField(db_column='id_bita_cbap', primary_key=True, serialize=False)),
                ('fecha_bita_cbap', models.DateTimeField(auto_now=True, db_column='fecha_bita_cbap')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('guardada', 'Guardada'), ('enviada', 'Enviada'), ('revisada', 'Revisada'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], default='guardada', max_length=20)),
                ('nombre_user_destino', models.CharField(blank=True, db_column='nombre_user_destino', default='-', max_length=250)),
                ('observaciones_cbap_estado', models.TextField(blank=True, db_column='observaciones', default='-', null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('firma_autorizador', models.ForeignKey(blank=True, db_column='firma_autorizador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitcoras_cbap_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('firma_revisor', models.ForeignKey(blank=True, db_column='firma_revisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitcoras_cbap_revisadas', to=settings.AUTH_USER_MODEL)),
                ('name_user_cbap', models.ForeignKey(db_column='name_user_cbap', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitcoras_cbap', to=settings.AUTH_USER_MODEL)),
                ('nombre_bita_cbap', models.ForeignKey(db_column='nombre_bita_cbap', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitcoras_cbap', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'bitcoras_cbap',
            },
        ),
        migrations.CreateModel(
            name='ClaveMuestraCbap',
            fields=[
                ('id_c_m', models.AutoField(db_column='id_c_m', primary_key=True, serialize=False)),
                ('fecha_c_m', models.DateTimeField(auto_now_add=True)),
                ('clave_c_m', models.CharField(blank=True, db_column='clave_c_m', default='-', max_length=50, null=True)),
                ('cantidad_c_m', models.CharField(blank=True, db_column='cantidad_c_m', default='-', max_length=50, null=True)),
                ('id_cbap_c_m', models.ForeignKey(db_column='id_cbap_c_m', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClaveMuestra', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'clave_muestra',
            },
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id_cc', models.AutoField(db_column='id_cc', primary_key=True, serialize=False)),
                ('nombre_laf', models.CharField(blank=True, db_column='nombre_laf', default='---', max_length=250, null=True)),
                ('fecha_1cc', models.DateField(blank=True, db_column='fecha_1cc', null=True)),
                ('page_1cc', models.CharField(blank=True, db_column='page_1cc', default='---', max_length=50, null=True)),
                ('id_cbap_cc', models.ForeignKey(db_column='id_cbap_cc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_calidades', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'verbose_name': 'Control de Calidad',
                'verbose_name_plural': 'Controles de Calidad',
                'db_table': 'Control_calidad',
            },
        ),
        migrations.CreateModel(
            name='Dilucion',
            fields=[
                ('id_d', models.AutoField(db_column='id_d', primary_key=True, serialize=False)),
                ('placa_d', models.DecimalField(blank=True, db_column='placa_d', decimal_places=5, default=None, max_digits=10, null=True)),
                ('placa_d2', models.DecimalField(blank=True, db_column='placa_d2', decimal_places=5, default=None, max_digits=10, null=True)),
                ('promedio_d', models.CharField(blank=True, db_column='promedio_d', default='---', max_length=250, null=True)),
                ('placa_d_2', models.DecimalField(blank=True, db_column='placa_d_2', decimal_places=5, default=None, max_digits=10, null=True)),
                ('placa_d2_2', models.DecimalField(blank=True, db_column='placa_d2_2', decimal_places=5, default=None, max_digits=10, null=True)),
                ('promedio_d_2', models.CharField(blank=True, db_column='promedio_d_2', default='---', max_length=250, null=True)),
                ('id_cbap_d', models.ForeignKey(db_column='id_cbap_d', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dilucion', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'dilucion',
            },
        ),
        migrations.CreateModel(
            name='DilucionesEmpleadas',
            fields=[
                ('id_dE', models.AutoField(db_column='id_d', primary_key=True, serialize=False)),
                ('dE_1', models.FloatField(db_column='dE_1', default=0.0, null=True)),
                ('dE_2', models.FloatField(db_column='dE_2', default=0.0, null=True)),
                ('dE_3', models.FloatField(db_column='dE_3', default=0.0, null=True)),
                ('dE_4', models.FloatField(db_column='dE_4', default=0.0, null=True)),
                ('id_cbap_dE', models.ForeignKey(db_column='id_cbap_dE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dilucion_empleadas', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'diluciones_empleadas',
            },
        ),
        migrations.CreateModel(
            name='Direct_o_Dilucion',
            fields=[
                ('id_dD', models.AutoField(db_column='id_dD', primary_key=True, serialize=False)),
                ('placa_dD', models.DecimalField(blank=True, db_column='placa_dD', decimal_places=5, default=None, max_digits=10, null=True)),
                ('placa_dD2', models.DecimalField(blank=True, db_column='placa_dD2', decimal_places=5, default=None, max_digits=10, null=True)),
                ('promedio_dD', models.CharField(blank=True, db_column='promedio_dD', default='---', max_length=250, null=True)),
                ('id_cbap_dD', models.ForeignKey(db_column='id_cbap_dD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dilucion_directa', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'direct_o_dilucion',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_r', models.AutoField(db_column='id_r', primary_key=True, serialize=False)),
                ('resultado_r', models.CharField(blank=True, db_column='resultado_r', max_length=250, null=True)),
                ('ufC_placa_r', models.CharField(blank=True, db_column='ufC_placa_r', max_length=250, null=True)),
                ('diferencia_r', models.CharField(blank=True, db_column='diferencia_r', max_length=250, null=True)),
                ('id_cbap_r', models.ForeignKey(db_column='id_cbap_r', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'resultado_pro',
            },
        ),
        migrations.CreateModel(
            name='VerificacionBalanza',
            fields=[
                ('id_vb', models.AutoField(db_column='id_cc', primary_key=True, serialize=False)),
                ('hora_vb', models.TimeField(blank=True, db_column='hora_vb', null=True)),
                ('actividad_vb', models.CharField(blank=True, db_column='actividad_vb', default='---', max_length=50, null=True)),
                ('ajuste_vb', models.CharField(blank=True, db_column='ajuste_vb', default='---', max_length=50, null=True)),
                ('valor_nominal_vb', models.CharField(blank=True, db_column='valor_nominal_vb', default='---', max_length=50, null=True)),
                ('valor_convencional_vb', models.CharField(blank=True, db_column='valor_convencional_vb', default='---', max_length=50, null=True)),
                ('valo_masa_vb', models.CharField(blank=True, db_column='valo_masa_vb', default='---', max_length=50, null=True)),
                ('diferecnia_vb', models.CharField(blank=True, db_column='diferecnia_vb', default='---', max_length=50, null=True)),
                ('incertidumbre_vb', models.CharField(blank=True, db_column='incertidumbre_vb', default='---', max_length=50, null=True)),
                ('emt_vb', models.CharField(blank=True, db_column='emt_vb', default='---', max_length=50, null=True)),
                ('aceptacion_vb', models.CharField(blank=True, db_column='aceptacion_vb', default='---', max_length=50, null=True)),
                ('valor_pesado_muestra_vb', models.CharField(blank=True, db_column='valor_pesado_muestra_vb', default='---', max_length=50, null=True)),
                ('fecha_vb', models.DateField(auto_now_add=True)),
                ('tomo_verficacion_vb', models.CharField(blank=True, db_column='tomo_verficacion_vb', default='---', max_length=50, null=True)),
                ('pagina_verficacion_vb', models.CharField(blank=True, db_column='pagina_verficacion_vb', default='---', max_length=50, null=True)),
                ('id_cbap_vb', models.ForeignKey(db_column='id_cbap_vb', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_balanza', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'verificacion_balanza',
            },
        ),
    ]
