# Generated by Django 5.1.6 on 2025-03-25 20:07

# Generated by Django 5.1.6 on 2025-03-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0002_datoscampocbap_bita_cbap_bitcoras_cbap_and_more'),
    ]

    operations = [
        # Verificar si fecha_1cc existe y crearla si no
        migrations.RunSQL(
            """
            SET @var = (SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'Control_calidad' 
                AND COLUMN_NAME = 'fecha_1cc');
            SET @sql = IF(@var = 0, 'ALTER TABLE Control_calidad ADD COLUMN fecha_1cc DATE NULL', 'SELECT 1');
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 1;"
        ),
    ]