# Generated by Django 5.1.6 on 2025-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0002_datoscampocbap_bita_cbap_bitcoras_cbap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
