# Generated by Django 5.1.6 on 2025-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0003_bitcoras_cbap_fecha_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='estado',
            field=models.CharField(choices=[('guardada', 'Guardada'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='guardada', max_length=20),
        ),
    ]
