# Generated by Django 5.1.6 on 2025-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0004_bitcoras_cbap_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bita_cbap',
            name='pagina_cbap',
            field=models.IntegerField(db_column='pagina_cbap', default=0, null=True),
        ),
    ]
