# Generated by Django 5.1.6 on 2025-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0004_alter_bita_cbap_mes_muestra_cbap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d',
            field=models.CharField(blank=True, db_column='placa_d', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d2',
            field=models.CharField(blank=True, db_column='placa_d2', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d2_2',
            field=models.CharField(blank=True, db_column='placa_d2_2', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d_2',
            field=models.CharField(blank=True, db_column='placa_d_2', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='direct_o_dilucion',
            name='placa_dD',
            field=models.CharField(blank=True, db_column='placa_dD', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='direct_o_dilucion',
            name='placa_dD2',
            field=models.CharField(blank=True, db_column='placa_dD2', default='---', max_length=250, null=True),
        ),
    ]
