# Generated by Django 5.1.6 on 2025-03-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0005_alter_dilucion_placa_d_alter_dilucion_placa_d2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bita_cbap',
            name='mes_muestra_cbap',
            field=models.CharField(blank=True, db_column='mes_muestra_cbap', max_length=50, null=True),
        ),
    ]
