# Generated by Django 5.1.6 on 2025-03-13 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0005_alter_bita_cbap_pagina_cbap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='nombre_user_destino',
            field=models.ForeignKey(db_column='usuario_creador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitcoras_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='observaciones_cbap_estado',
            field=models.TextField(blank=True, db_column='observaciones', default='-', null=True),
        ),
    ]
