# Generated by Django 5.1.6 on 2025-03-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0006_bitcoras_cbap_nombre_user_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoras_cbap',
            name='nombre_user_destino',
            field=models.CharField(blank=True, db_column='nombre_user_destino', default='-', max_length=250),
        ),
    ]
