# Generated by Django 5.1.6 on 2025-03-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0006_alter_bita_cbap_mes_muestra_cbap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bita_cbap',
            name='mes_muestra_cbap',
            field=models.DateField(blank=True, db_column='mes_muestra_cbap', null=True),
        ),
    ]
