# Generated by Django 5.1.6 on 2025-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0007_alter_bitcoras_cbap_nombre_user_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='ajuste_vb',
            field=models.CharField(blank=True, db_column='ajuste_vb', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='diferecnia_vb',
            field=models.CharField(blank=True, db_column='diferecnia_vb', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='emt_vb',
            field=models.CharField(blank=True, db_column='emt_vb', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='incertidumbre_vb',
            field=models.CharField(blank=True, db_column='incertidumbre_vb', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valo_masa_vb',
            field=models.CharField(blank=True, db_column='valo_masa_vb', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valor_convencional_vb',
            field=models.CharField(blank=True, db_column='valor_convencional_vb', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valor_nominal_vb',
            field=models.CharField(blank=True, db_column='valor_nominal_vb', default='-', max_length=50, null=True),
        ),
    ]
