# Generated by Django 5.1.6 on 2025-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0007_alter_bita_cbap_mes_muestra_cbap'),
    ]

    operations = [
        migrations.AddField(
            model_name='clavemuestracbap',
            name='medicion_c_m',
            field=models.CharField(blank=True, db_column='medicion_c_m', default='-', max_length=50, null=True),
        ),
    ]
