# Generated by Django 5.1.6 on 2025-03-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0008_alter_verificacionbalanza_ajuste_vb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bita_cbap',
            name='estado',
        ),
    ]
