# Generated by Django 5.1.6 on 2025-03-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0009_clavemuestracbap_cantidad_blanco_c_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dilucion',
            name='placa_blanco_d',
        ),
        migrations.AddField(
            model_name='direct_o_dilucion',
            name='placa_blanco_dD',
            field=models.CharField(blank=True, db_column='placa_blanco_dD', default='---', max_length=250, null=True),
        ),
    ]
