# Generated by Django 5.1.6 on 2025-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0009_remove_bita_cbap_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='hora_vb',
            field=models.CharField(blank=True, db_column='hora_vb', max_length=50, null=True),
        ),
    ]
