# Generated by Django 5.1.6 on 2025-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0010_remove_dilucion_placa_blanco_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilucionesempleadas',
            name='dE_1',
            field=models.FloatField(blank=True, db_column='dE_1', default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dilucionesempleadas',
            name='dE_2',
            field=models.FloatField(blank=True, db_column='dE_2', default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dilucionesempleadas',
            name='dE_3',
            field=models.FloatField(blank=True, db_column='dE_3', default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dilucionesempleadas',
            name='dE_4',
            field=models.FloatField(blank=True, db_column='dE_4', default=0.0, null=True),
        ),
    ]
