# Generated by Django 5.1.6 on 2025-03-19 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0010_alter_verificacionbalanza_hora_vb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='firma_revisor',
            field=models.ForeignKey(blank=True, db_column='firma_revisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitcoras_cbap_revisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
