# Generated by Django 5.1.6 on 2025-03-19 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0011_bitcoras_cbap_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='firma_autorizador',
            field=models.ForeignKey(blank=True, db_column='firma_autorizador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitcoras_cbap_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bitcoras_cbap',
            name='estado',
            field=models.CharField(choices=[('guardada', 'Guardada'), ('enviada', 'Enviada'), ('revisada', 'Revisada'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], default='guardada', max_length=20),
        ),
    ]
