# Generated by Django 5.1.6 on 2025-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0011_alter_dilucionesempleadas_de_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableBlanco',
            fields=[
                ('id_blanco', models.AutoField(db_column='id_blanco', primary_key=True, serialize=False)),
                ('cantidad_blanco', models.CharField(blank=True, db_column='cantidad_blanco', default='---', max_length=50, null=True)),
                ('placa_blanco', models.CharField(blank=True, db_column='placa_blanco', default='---', max_length=250, null=True)),
                ('resultado_blanco', models.CharField(blank=True, db_column='resultado_blanco', max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='direct_o_dilucion',
            name='placa_blanco_dD',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='resultado_blanco_r',
        ),
    ]
