# Generated by Django 5.1.6 on 2025-03-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0012_bitcoras_cbap_fecha_autorizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='diferencia_r',
            field=models.CharField(blank=True, db_column='diferencia_r', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado_r',
            field=models.CharField(blank=True, db_column='resultado_r', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='ufC_placa_r',
            field=models.CharField(blank=True, db_column='ufC_placa_r', default='---', max_length=250, null=True),
        ),
    ]
