# Generated by Django 5.1.6 on 2025-03-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0013_remove_clavemuestracbap_cantidad_blanco_c_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableblanco',
            name='nombre_bita_cbap',
            field=models.ForeignKey(db_column='nombre_bita_cbap_blancos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_blancos', to='ICAYS_BIT.bita_cbap'),
        ),
        migrations.AlterModelTable(
            name='tableblanco',
            table='blancos_cbap',
        ),
    ]
