# Generated by Django 5.1.6 on 2025-03-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0013_alter_resultado_diferencia_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='fecha_1cc',
            field=models.CharField(blank=True, db_column='fecha_1cc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='nombre_laf',
            field=models.CharField(db_column='nombre_laf', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='page_1cc',
            field=models.CharField(db_column='page_1cc', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='fecha_siembra_dc',
            field=models.CharField(blank=True, db_column='fecha_siembra_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_incubacion_dc',
            field=models.CharField(blank=True, db_column='hora_incubacion_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_siembra_dc',
            field=models.CharField(blank=True, db_column='hora_siembra_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='aceptacion_vb',
            field=models.CharField(blank=True, db_column='aceptacion_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='actividad_vb',
            field=models.CharField(blank=True, db_column='actividad_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='ajuste_vb',
            field=models.CharField(blank=True, db_column='ajuste_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='diferecnia_vb',
            field=models.CharField(blank=True, db_column='diferecnia_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='emt_vb',
            field=models.CharField(blank=True, db_column='emt_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='incertidumbre_vb',
            field=models.CharField(blank=True, db_column='incertidumbre_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valo_masa_vb',
            field=models.CharField(blank=True, db_column='valo_masa_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valor_convencional_vb',
            field=models.CharField(blank=True, db_column='valor_convencional_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valor_nominal_vb',
            field=models.CharField(blank=True, db_column='valor_nominal_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='valor_pesado_muestra_vb',
            field=models.CharField(blank=True, db_column='valor_pesado_muestra_vb', default='---', max_length=50, null=True),
        ),
    ]
