# Generated by Django 5.1.6 on 2025-03-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0014_alter_controlcalidad_fecha_1cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bita_cbap',
            name='fecha_lectura_cbap',
            field=models.CharField(blank=True, db_column='fecha_lectura_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='hora_lectura_cbap',
            field=models.CharField(blank=True, db_column='hora_lectura_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='letra_analista_cbap',
            field=models.CharField(blank=True, db_column='numero_analista_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='mes_muestra_cbap',
            field=models.CharField(blank=True, db_column='mes_muestra_cbap', default='-', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='numero_agar_cbap',
            field=models.CharField(blank=True, db_column='numero_agar_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='numero_fosfato_cbap',
            field=models.CharField(blank=True, db_column='numero_fosfato_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='pagina_agar_cbap',
            field=models.CharField(blank=True, db_column='pagina_agar_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='pagina_fosfato_cbap',
            field=models.CharField(blank=True, db_column='pagina_fosfato_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='pagina_muestra_cbap',
            field=models.CharField(blank=True, db_column='pagina_muestra_cbap', default='---', max_length=250, null=True),
        ),
    ]
