# Generated by Django 5.1.6 on 2025-03-31 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0014_tableblanco_nombre_bita_cbap_alter_tableblanco_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejemplosFormulas',
            fields=[
                ('id_ejemplos', models.AutoField(db_column='id_ejemplos', primary_key=True, serialize=False)),
                ('dato1_ejemplo', models.CharField(blank=True, db_column='dato1_ejemplo', default='---', max_length=50, null=True)),
                ('dato2_ejemplo', models.CharField(blank=True, db_column='dato2_ejemplo', default='---', max_length=50, null=True)),
                ('dato3_ejemplo', models.CharField(blank=True, db_column='dato3_ejemplo', default='---', max_length=50, null=True)),
                ('resultdo_ejemplo', models.CharField(blank=True, db_column='resultdo_ejemplo', default='---', max_length=50, null=True)),
                ('clave_muestra_ejemplo', models.CharField(blank=True, db_column='clave_muestra_ejemplo', default='---', max_length=50, null=True)),
                ('nombre_bita_cbap', models.ForeignKey(db_column='nombre_bita_cbap_ejemplos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejemplos_cbap', to='ICAYS_BIT.bita_cbap')),
            ],
            options={
                'db_table': 'ejemplos_cbap',
            },
        ),
    ]
