# Generated by Django 5.1.6 on 2025-03-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0015_alter_bita_cbap_fecha_lectura_cbap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='nombre_laf',
            field=models.CharField(blank=True, db_column='nombre_laf', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='page_1cc',
            field=models.CharField(blank=True, db_column='page_1cc', default='---', max_length=50, null=True),
        ),
    ]
