# Generated by Django 5.1.6 on 2025-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0016_alter_controlcalidad_nombre_laf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionbalanza',
            name='pagina_verficacion_vb',
            field=models.CharField(blank=True, db_column='pagina_verficacion_vb', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificacionbalanza',
            name='tomo_verficacion_vb',
            field=models.CharField(blank=True, db_column='tomo_verficacion_vb', default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d',
            field=models.DecimalField(blank=True, db_column='placa_d', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d2',
            field=models.DecimalField(blank=True, db_column='placa_d2', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d2_2',
            field=models.DecimalField(blank=True, db_column='placa_d2_2', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='placa_d_2',
            field=models.DecimalField(blank=True, db_column='placa_d_2', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='promedio_d',
            field=models.DecimalField(blank=True, db_column='promedio_d', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='promedio_d_2',
            field=models.DecimalField(blank=True, db_column='promedio_d_2', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='direct_o_dilucion',
            name='placa_dD',
            field=models.DecimalField(blank=True, db_column='placa_dD', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='direct_o_dilucion',
            name='placa_dD2',
            field=models.DecimalField(blank=True, db_column='placa_dD2', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='direct_o_dilucion',
            name='promedio_dD',
            field=models.DecimalField(blank=True, db_column='promedio_dD', decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='diferencia_r',
            field=models.CharField(blank=True, db_column='diferencia_r', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado_r',
            field=models.CharField(blank=True, db_column='resultado_r', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='ufC_placa_r',
            field=models.CharField(blank=True, db_column='ufC_placa_r', max_length=250, null=True),
        ),
    ]
