# Generated by Django 5.1.6 on 2025-04-01 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0016_alter_ejemplosformulas_nombre_bita_cbap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(db_column='id_notification', primary_key=True, serialize=False)),
                ('message', models.CharField(db_column='message', max_length=255)),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('recipient', models.ForeignKey(db_column='recipient', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_ejemplo', models.ForeignKey(blank=True, db_column='related_ejemplo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ICAYS_BIT.ejemplosformulas')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id_subscription', models.AutoField(db_column='id_subscription', primary_key=True, serialize=False)),
                ('endpoint', models.TextField(db_column='endpoint')),
                ('p256dh', models.TextField(db_column='p256dh')),
                ('auth', models.TextField(db_column='auth')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
