# Generated by Django 5.1.6 on 2025-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0017_verificacionbalanza_pagina_verficacion_vb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscampocbap',
            name='fecha_siembra_dc',
            field=models.DateField(blank=True, db_column='fecha_siembra_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_incubacion_dc',
            field=models.TimeField(blank=True, db_column='hora_incubacion_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_siembra_dc',
            field=models.TimeField(blank=True, db_column='hora_siembra_dc', default='---', max_length=250, null=True),
        ),
    ]
