# Generated by Django 5.1.6 on 2025-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0018_remove_bita_cbap_fecha_lectura_cbap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturas',
            options={},
        ),
        migrations.RemoveField(
            model_name='lecturas',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='lecturas',
            name='hora_lectura',
        ),
        migrations.AddField(
            model_name='lecturas',
            name='fecha_lectura_1',
            field=models.CharField(blank=True, db_column='fecha_lectura_1', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturas',
            name='fecha_lectura_2',
            field=models.CharField(blank=True, db_column='fecha_lectura_2', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturas',
            name='hora_lectura_1',
            field=models.CharField(blank=True, db_column='hora_lectura_1', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturas',
            name='hora_lectura_2',
            field=models.CharField(blank=True, db_column='hora_lectura_2', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturas',
            name='hora_lectura_3',
            field=models.CharField(blank=True, db_column='hora_lectura_3', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturas',
            name='hora_lectura_4',
            field=models.CharField(blank=True, db_column='hora_lectura_4', default='---', max_length=50, null=True),
        ),
    ]
