# Generated by Django 5.1.6 on 2025-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0018_alter_datoscampocbap_fecha_siembra_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_incubacion_dc',
            field=models.CharField(blank=True, db_column='hora_incubacion_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_siembra_dc',
            field=models.CharField(blank=True, db_column='hora_siembra_dc', default='---', max_length=250, null=True),
        ),
    ]
