# Generated by Django 5.1.6 on 2025-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0019_alter_lecturas_options_remove_lecturas_fecha_lectura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturas',
            name='fecha_lectura_1',
            field=models.DateField(blank=True, db_column='fecha_lectura_1', null=True),
        ),
        migrations.AlterField(
            model_name='lecturas',
            name='fecha_lectura_2',
            field=models.DateField(blank=True, db_column='fecha_lectura_2', null=True),
        ),
        migrations.AlterField(
            model_name='lecturas',
            name='hora_lectura_1',
            field=models.TimeField(blank=True, db_column='hora_lectura_1', null=True),
        ),
        migrations.AlterField(
            model_name='lecturas',
            name='hora_lectura_2',
            field=models.TimeField(blank=True, db_column='hora_lectura_2', null=True),
        ),
        migrations.AlterField(
            model_name='lecturas',
            name='hora_lectura_3',
            field=models.TimeField(blank=True, db_column='hora_lectura_3', null=True),
        ),
        migrations.AlterField(
            model_name='lecturas',
            name='hora_lectura_4',
            field=models.TimeField(blank=True, db_column='hora_lectura_4', null=True),
        ),
    ]
