# Generated by Django 5.1.6 on 2025-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0019_alter_datoscampocbap_hora_incubacion_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bita_cbap',
            name='fecha_lectura_cbap',
            field=models.DateField(blank=True, db_column='fecha_lectura_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='hora_lectura_cbap',
            field=models.TimeField(blank=True, db_column='hora_lectura_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_incubacion_dc',
            field=models.TimeField(blank=True, db_column='hora_incubacion_dc', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_siembra_dc',
            field=models.TimeField(blank=True, db_column='hora_siembra_dc', default='---', max_length=250, null=True),
        ),
    ]
