# Generated by Django 5.1.6 on 2025-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0020_alter_bita_cbap_fecha_lectura_cbap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='hora_vb',
            field=models.TimeField(blank=True, db_column='hora_vb', max_length=50, null=True),
        ),
    ]
