# Generated by Django 5.1.6 on 2025-04-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0020_alter_lecturas_fecha_lectura_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturas',
            name='hora_lectura_3',
        ),
        migrations.RemoveField(
            model_name='lecturas',
            name='hora_lectura_4',
        ),
    ]
