# Generated by Django 5.1.6 on 2025-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0021_remove_lecturas_hora_lectura_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bita_cbap',
            name='año_muestra_cbap',
            field=models.CharField(blank=True, db_column='año_muestra_cbap', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='mes_muestra_cbap',
            field=models.CharField(blank=True, db_column='mes_muestra_cbap', default='---', max_length=250, null=True),
        ),
    ]
