# Generated by Django 5.1.6 on 2025-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0021_alter_verificacionbalanza_hora_vb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='fecha_1cc',
            field=models.DateField(blank=True, db_column='fecha_1cc', default='---', max_length=250, null=True),
        ),
    ]
