# Generated by Django 5.1.6 on 2025-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0022_alter_controlcalidad_fecha_1cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bita_cbap',
            name='fecha_lectura_cbap',
            field=models.DateField(blank=True, db_column='fecha_lectura_cbap', null=True),
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='hora_lectura_cbap',
            field=models.TimeField(blank=True, db_column='hora_lectura_cbap', null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='fecha_siembra_dc',
            field=models.DateField(blank=True, db_column='fecha_siembra_dc', null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_incubacion_dc',
            field=models.TimeField(blank=True, db_column='hora_incubacion_dc', null=True),
        ),
        migrations.AlterField(
            model_name='datoscampocbap',
            name='hora_siembra_dc',
            field=models.TimeField(blank=True, db_column='hora_siembra_dc', null=True),
        ),
        migrations.AlterField(
            model_name='verificacionbalanza',
            name='hora_vb',
            field=models.TimeField(blank=True, db_column='hora_vb', null=True),
        ),
    ]
