# Generated by Django 5.1.6 on 2025-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0022_bita_cbap_año_muestra_cbap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacionbalanza',
            name='tomo_verficacion_vb',
        ),
        migrations.AddField(
            model_name='verificacionbalanza',
            name='anio_verficacion_vb',
            field=models.CharField(blank=True, db_column='anio_verficacion_vb', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificacionbalanza',
            name='mes_verficacion_vb',
            field=models.CharField(blank=True, db_column='mes_verficacion_vb', default='---', max_length=50, null=True),
        ),
    ]
