# Generated by Django 5.1.6 on 2025-04-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0023_remove_verificacionbalanza_tomo_verficacion_vb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='fecha_1cc',
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='anio_1cc',
            field=models.CharField(blank=True, db_column='anio_1cc', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='mes_1cc',
            field=models.CharField(blank=True, db_column='mes_1cc', default='---', max_length=50, null=True),
        ),
    ]
