# Generated by Django 5.1.6 on 2025-03-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0023_alter_bita_cbap_fecha_lectura_cbap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilucion',
            name='promedio_d',
            field=models.CharField(blank=True, db_column='promedio_d', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dilucion',
            name='promedio_d_2',
            field=models.CharField(blank=True, db_column='promedio_d_2', default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='direct_o_dilucion',
            name='promedio_dD',
            field=models.CharField(blank=True, db_column='promedio_dD', default='---', max_length=250, null=True),
        ),
    ]
