# Generated by Django 5.1.6 on 2025-03-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0024_alter_dilucion_promedio_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacionbalanza',
            name='pagina_verficacion_vb',
        ),
        migrations.RemoveField(
            model_name='verificacionbalanza',
            name='tomo_verficacion_vb',
        ),
    ]
