# Generated by Django 5.1.6 on 2025-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0024_remove_controlcalidad_fecha_1cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoras_cbap',
            name='campos_seleccionados',
            field=models.TextField(blank=True, db_column='campos_seleccionados', help_text='JSON con los IDs de los campos seleccionados y sus observaciones', null=True),
        ),
    ]
