# Generated by Django 5.1.6 on 2025-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0025_remove_verificacionbalanza_pagina_verficacion_vb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionbalanza',
            name='pagina_verficacion_vb',
            field=models.CharField(blank=True, db_column='pagina_verficacion_vb', default='---', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificacionbalanza',
            name='tomo_verficacion_vb',
            field=models.CharField(blank=True, db_column='tomo_verficacion_vb', default='---', max_length=50, null=True),
        ),
    ]
