# Generated by Django 5.1.6 on 2025-04-14 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0025_bitcoras_cbap_campos_seleccionados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoras_cbap',
            name='campos_seleccionados',
        ),
        migrations.RemoveField(
            model_name='bitcoras_cbap',
            name='observaciones_cbap_estado',
        ),
        migrations.AlterField(
            model_name='bita_cbap',
            name='observaciones_cbap',
            field=models.TextField(blank=True, db_column='observaciones_cbap', default='---', null=True),
        ),
        migrations.CreateModel(
            name='ObservacionCampo',
            fields=[
                ('id_valor_editado', models.AutoField(db_column='id_valor_editado', primary_key=True, serialize=False)),
                ('campo_id', models.CharField(db_column='campo_id', max_length=255)),
                ('campo_nombre', models.CharField(db_column='campo_nombre', max_length=255)),
                ('valor_original', models.TextField(db_column='valor_original')),
                ('valor_editado', models.TextField(db_column='valor_editado')),
                ('fecha_edicion', models.DateTimeField(auto_now_add=True, db_column='fecha_edicion')),
                ('bitacora', models.ForeignKey(db_column='bitacora_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores_editados', to='ICAYS_BIT.bitcoras_cbap')),
                ('editado_por', models.ForeignKey(db_column='editado_por', on_delete=django.db.models.deletion.CASCADE, related_name='valores_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'valores_editados',
                'ordering': ['-fecha_edicion'],
                'unique_together': {('bitacora', 'campo_id')},
            },
        ),
    ]
