# Generated by Django 5.1.6 on 2025-04-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0026_remove_bitcoras_cbap_campos_seleccionados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacioncampo',
            name='valor_editado',
        ),
        migrations.AddField(
            model_name='observacioncampo',
            name='campo_tipo',
            field=models.TextField(blank=True, db_column='campo_tipo', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='observacioncampo',
            name='observacion',
            field=models.CharField(blank=True, db_column='observacion', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='observacioncampo',
            name='valor_original',
            field=models.TextField(blank=True, db_column='valor_original', max_length=250, null=True),
        ),
    ]
