# Generated by Django 5.1.6 on 2025-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0027_remove_observacioncampo_valor_editado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacioncampo',
            name='contador_ediciones',
            field=models.PositiveIntegerField(db_column='contador_ediciones', default=0, help_text='Contador de veces que se ha editado este campo'),
        ),
        migrations.AddField(
            model_name='observacioncampo',
            name='historial_ediciones',
            field=models.JSONField(blank=True, db_column='historial_ediciones', help_text='Historial de ediciones en formato JSON', null=True),
        ),
    ]
