# Generated by Django 5.1.6 on 2025-04-16 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0028_observacioncampo_contador_ediciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacioncampo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de edición'), ('editado', 'Editado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado nuevamente')], db_column='estado', default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='observacioncampo',
            name='observacion_por',
            field=models.ForeignKey(db_column='observacion_por', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacioncampo',
            name='editado_por',
            field=models.ForeignKey(blank=True, db_column='editado_por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_editados', to=settings.AUTH_USER_MODEL),
        ),
    ]
