# Generated by Django 5.1.6 on 2025-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0029_observacioncampo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacioncampo',
            name='valor_actual',
            field=models.TextField(blank=True, db_column='valor_actual', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='observacioncampo',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_edicion'),
        ),
    ]
