# Generated by Django 5.1.6 on 2025-04-23 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0030_observacioncampo_valor_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAutorizacion',
            fields=[
                ('id_solicitud', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('campo_id', models.CharField(db_column='campo_id', help_text='ID del campo que requiere autorización', max_length=100)),
                ('campo_nombre', models.CharField(db_column='campo_nombre', help_text='Nombre descriptivo del campo', max_length=255)),
                ('valor_actual', models.TextField(blank=True, db_column='valor_actual', help_text='Valor actual del campo', null=True)),
                ('valor_propuesto', models.TextField(blank=True, db_column='valor_propuesto', help_text='Valor que se desea asignar', null=True)),
                ('tipo_solicitud', models.CharField(choices=[('edicion_campo_calculado', 'Edición Campo Calculado'), ('edicion_resultado', 'Edición Resultado'), ('edicion_formula', 'Edición Fórmula')], db_column='tipo_solicitud', max_length=50)),
                ('justificacion', models.TextField(blank=True, db_column='justificacion', help_text='Razón por la que se solicita el cambio', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_column='estado', default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, db_column='fecha_solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, db_column='fecha_respuesta', null=True)),
                ('respuesta_supervisor', models.TextField(blank=True, db_column='respuesta_supervisor', help_text='Comentarios del supervisor al aprobar/rechazar', null=True)),
                ('bitacora', models.ForeignKey(db_column='bitacora_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_autorizacion', to='ICAYS_BIT.bitcoras_cbap')),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('supervisor_asignado', models.ForeignKey(blank=True, db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Autorización',
                'verbose_name_plural': 'Solicitudes de Autorización',
                'db_table': 'solicitudes_autorizacion',
                'ordering': ['-fecha_solicitud'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('bitacora', 'campo_id', 'solicitante'), name='unique_pending_request')],
            },
        ),
    ]
