# Generated by Django 5.1.6 on 2025-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0031_solicitudautorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudautorizacion',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='solicitudautorizacion',
            name='justificacion',
        ),
        migrations.RemoveField(
            model_name='solicitudautorizacion',
            name='respuesta_supervisor',
        ),
        migrations.RemoveField(
            model_name='solicitudautorizacion',
            name='supervisor_asignado',
        ),
        migrations.RemoveField(
            model_name='solicitudautorizacion',
            name='tipo_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudautorizacion',
            name='valor_propuesto',
        ),
        migrations.AlterField(
            model_name='solicitudautorizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_column='estado', default='pendiente', max_length=20),
        ),
    ]
