# Generated by Django 5.1.6 on 2025-04-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0032_remove_solicitudautorizacion_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_bitacora',
            field=models.ForeignKey(blank=True, db_column='related_bitacora', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ICAYS_BIT.bitcoras_cbap'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(db_column='type', default='general', max_length=50),
        ),
    ]
