# Generated by Django 5.1.6 on 2025-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0033_notification_related_bitacora_notification_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solicitudautorizacion',
            name='unique_pending_request',
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['bitacora', 'campo_id', 'solicitante', 'estado'], name='idx_solicitud_estado'),
        ),
    ]
