# Generated by Django 5.1.6 on 2025-04-25 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0034_remove_solicitudautorizacion_unique_pending_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudautorizacion',
            name='supervisor',
            field=models.ForeignKey(db_column='supervisor_id', default=3, help_text='Usuario que debe autorizar la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_por_revisar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
