# Generated by Django 5.1.6 on 2025-05-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0035_solicitudautorizacion_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(db_column='priority', default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, db_column='url', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('revision', 'Revisión'), ('autorizacion', 'Autorización'), ('rechazo', 'Rechazo'), ('edicion', 'Edición')], db_column='type', default='general', max_length=50),
        ),
    ]
