# Generated by Django 5.1.6 on 2025-05-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0036_notification_priority_notification_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscampocbap',
            old_name='id_dc',
            new_name='id_dc_cbap',
        ),
        migrations.RemoveField(
            model_name='bita_cbap',
            name='id_dc_cbap',
        ),
        migrations.AddField(
            model_name='datoscampocbap',
            name='nombre_bita_cbap',
            field=models.ForeignKey(blank=True, db_column='nombre_bita_cbap_dc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_campo_adicionales', to='ICAYS_BIT.bita_cbap'),
        ),
    ]
