# Generated by Django 5.1.6 on 2025-05-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAYS_BIT', '0037_rename_id_dc_datoscampocbap_id_dc_cbap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscampocbap',
            old_name='id_dc_cbap',
            new_name='id_dc',
        ),
        migrations.RemoveField(
            model_name='datoscampocbap',
            name='nombre_bita_cbap',
        ),
        migrations.AddField(
            model_name='bita_cbap',
            name='id_dc_cbap',
            field=models.ForeignKey(db_column='id_dc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bita_cbap', to='ICAYS_BIT.datoscampocbap'),
        ),
    ]
